#!/usr/bin/env python3
# Regenerate src/tables.rs from the reference C++ (tools/ref/arrays.h + pack.cc).
# Usage: python3 tools/gen_tables.py
import re, os
HERE=os.path.dirname(os.path.abspath(__file__))
REF=os.path.join(HERE,"ref")
arrays=open(os.path.join(REF,"arrays.h")).read()
pack=open(os.path.join(REF,"pack.cc")).read()
def grab_block(text, marker):
    i=text.index(marker); i=text.index('{',i); depth=0; j=i
    while True:
        if text[j]=='{': depth+=1
        elif text[j]=='}':
            depth-=1
            if depth==0: break
        j+=1
    return text[i:j+1]
def rows_of_ints(block):
    return [[int(x) for x in re.findall(r'-?\d+', r)] for r in re.findall(r'\{([^{}]*)\}', block)]
colorder=[int(x) for x in re.findall(r'-?\d+', grab_block(arrays,"int colorder[]"))]
Nm=rows_of_ints(grab_block(arrays,"int Nm[][7]"))
Mn=rows_of_ints(grab_block(arrays,"int Mn[][3]"))
gen=rows_of_ints(grab_block(pack,"int gen[87][87]"))
assert len(colorder)==174 and len(Nm)==87 and len(Mn)==174 and len(gen)==87
def fmt_flat(name,ty,arr,per):
    s=f"pub static {name}: [{ty}; {len(arr)}] = [\n"
    for i in range(0,len(arr),per): s+="    "+", ".join(map(str,arr[i:i+per]))+",\n"
    return s+"];\n"
def fmt_2d(name,ty,rows,inner):
    s=f"pub static {name}: [[{ty}; {inner}]; {len(rows)}] = [\n"
    for r in rows: s+="    ["+", ".join(map(str,r))+"],\n"
    return s+"];\n"
with open(os.path.join(HERE,"..","src","tables.rs"),"w") as f:
    f.write("//! LDPC(174,87) + Costas constants for JS8, from WSJT-X / JS8Call\n")
    f.write("//! (via the `fate` reference). Auto-generated by tools/gen_tables.py — do not edit.\n\n")
    f.write("/// JS8 Costas sync array (7 tones), used at symbol offsets 0, 36, 72.\n")
    f.write("pub static COSTAS: [usize; 7] = [4, 2, 5, 6, 1, 3, 0];\n\n")
    f.write("/// Permutation mapping the systematic encoder output to codeword bit order.\n")
    f.write(fmt_flat("COLORDER","usize",colorder,20)+"\n")
    f.write("/// LDPC generator: codeword bit i (0..87) = XOR of plain[j] where GEN[i][j]==1.\n")
    f.write(fmt_2d("GEN","u8",gen,87)+"\n")
    f.write("/// Parity rows: 1-origin codeword bits that must XOR to 0 (0 = unused).\n")
    f.write(fmt_2d("NM","u16",Nm,7)+"\n")
    f.write("/// For each codeword bit (1-origin), the three parity checks it joins.\n")
    f.write(fmt_2d("MN","u16",Mn,3))
print("wrote src/tables.rs")
